"""Draw Figure 4 for the AFMS manuscript.

This file contains plotting code only. It consumes normalized rows generated by
paper_asset_data.py or a CSV with the same fields.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from paper_asset_data import FINAL, collect_trainer_table


def apply_style() -> None:
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "DejaVu Sans"],
            "svg.fonttype": "none",
            "pdf.fonttype": 42,
            "font.size": 7,
            "axes.labelsize": 7,
            "axes.titlesize": 8,
            "xtick.labelsize": 6.5,
            "ytick.labelsize": 6.5,
            "legend.fontsize": 6.5,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.linewidth": 0.6,
            "xtick.major.width": 0.5,
            "ytick.major.width": 0.5,
            "xtick.major.size": 2.5,
            "ytick.major.size": 2.5,
            "legend.frameon": False,
        }
    )


def load_rows_from_csv(path: Path) -> list[dict]:
    numeric_fields = {
        "keypoints",
        "protocol_keypoints",
        "protocol_measurements",
        "protocol_skeleton",
        "protocol_lines",
        "protocol_angles",
        "protocol_ratios",
        "runtime_protocol",
        "runtime_detector",
        "runtime_pose",
        "train_images",
        "val_images",
        "train_annotations",
        "val_annotations",
        "det_map",
        "det_map50",
        "det_map75",
        "kp_pck",
        "kp_auc",
        "kp_nme",
    }
    with path.open("r", encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    for row in rows:
        for field in numeric_fields:
            if field not in row:
                continue
            value = row[field]
            row[field] = float(value) if "." in value else int(value)
    return rows


def plot_validation_report(rows: list[dict], output_dir: Path = FINAL) -> list[Path]:
    apply_style()

    blue = "#2F5F8F"
    orange = "#D98C3A"
    pale = "#F4F7FA"
    text = "#1B1B1B"
    muted = "#666666"

    fig, ax = plt.subplots(figsize=(7.4, 3.7))
    ax.set_axis_off()
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)

    ax.text(0.02, 0.96, "Protocol-defined validation report generated by the AFMS trainer", fontsize=9.5, fontweight="bold", va="top")
    ax.text(
        0.02,
        0.905,
        "Each row is an independent protocol-defined validation output. Values are reported for operational feasibility, not for cross-species ranking.",
        fontsize=6.4,
        color=muted,
        va="top",
    )

    columns = [
        ("Species protocol", 0.025, 0.205),
        ("Validation set", 0.225, 0.345),
        ("Landmarks", 0.365, 0.445),
        ("Detector validation", 0.475, 0.665),
        ("Keypoint validation", 0.705, 0.965),
    ]
    header_y = 0.80
    row_h = 0.12
    first_row_y = 0.70
    for title, x0, x1 in columns:
        ax.text(x0, header_y, title, fontsize=6.8, fontweight="bold", color=blue, va="center")
        ax.plot([x0, x1], [header_y - 0.028, header_y - 0.028], color=blue, lw=0.8)
    subheaders = [
        ("mAP", 0.475),
        ("@0.5", 0.545),
        ("@0.75", 0.615),
        ("PCK", 0.705),
        ("AUC", 0.775),
        ("NME", 0.845),
    ]
    for label, x0 in subheaders:
        ax.text(x0, header_y - 0.055, label, fontsize=5.8, color=muted, va="center")

    for idx, row in enumerate(rows):
        y = first_row_y - idx * row_h
        if idx % 2 == 0:
            ax.add_patch(plt.Rectangle((0.015, y - 0.055), 0.97, row_h * 0.82, color=pale, ec="none", zorder=-1))
        ax.text(0.025, y, row["label"], fontsize=7.2, fontweight="bold", va="center", color=text)
        ax.text(0.025, y - 0.035, row["scientific_name"], fontsize=5.7, va="center", color=muted, style="italic")

        ax.text(0.225, y + 0.018, f"{row['val_images']} images", fontsize=6.3, va="center", color=text)
        ax.text(0.225, y - 0.020, f"{row['val_annotations']} objects", fontsize=6.3, va="center", color=text)

        ax.text(0.365, y + 0.018, f"{row['keypoints']} keypoints", fontsize=6.3, va="center", color=text)
        ax.text(0.365, y - 0.020, "protocol-defined", fontsize=5.7, va="center", color=orange)

        metric_values = [
            (row["det_map"], 0.475),
            (row["det_map50"], 0.545),
            (row["det_map75"], 0.615),
            (row["kp_pck"], 0.705),
            (row["kp_auc"], 0.775),
            (row["kp_nme"], 0.845),
        ]
        for value, x0 in metric_values:
            ax.text(x0, y, f"{value:.3f}", fontsize=6.3, va="center", color=text)

    ax.plot([0.015, 0.985], [0.165, 0.165], color="#C9D3DC", lw=0.7)
    ax.text(
        0.02,
        0.125,
        "Validation metrics are produced after reading each species protocol and its corresponding validation annotations. Training-process information is not reported.",
        fontsize=6.1,
        color=muted,
        va="top",
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    outputs = []
    for ext, dpi in (("pdf", 300), ("svg", 300), ("png", 450), ("tiff", 600)):
        out = output_dir / f"fig_trainer_results.{ext}"
        fig.savefig(out, dpi=dpi, bbox_inches="tight", facecolor="white")
        outputs.append(out)
    plt.close(fig)
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description="Draw AFMS Figure 4 validation report.")
    parser.add_argument("--metrics-csv", type=Path, default=None, help="Optional CSV source generated by rebuild_paper_assets.py.")
    parser.add_argument("--output-dir", type=Path, default=FINAL)
    args = parser.parse_args()

    rows = load_rows_from_csv(args.metrics_csv) if args.metrics_csv else collect_trainer_table()
    for out in plot_validation_report(rows, args.output_dir):
        print(out)


if __name__ == "__main__":
    main()
